version: "3.9"

services:
  email-api:
    build: .
    container_name: acs-email-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped

    volumes:
      - email_logs:/app/logs

volumes:
  email_logs: